
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'video_streaming_analysis'
version: '1.0.0'
profile: 'my_profile'  # This should match the profile name in profiles.yml

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  video_streaming:
    dimension:
      +materialized: table
      +schema: dimension
    staging:
      +materialized: table
      +schema: staging
    intermediate:
      +materialized: table
      +schema: intermediate
    fact:
      +materialized: table
      +schema: fact
  example:
    +materialized: table
        